version: '2'
services:
    tidyup-app:
        image: tidyup
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://tidyup-postgresql:5432/tidyUp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=tidyup-elasticsearch:9300
        ports:
            - 8080:8080
    tidyup-postgresql:
        extends:
            file: postgresql.yml
            service: tidyup-postgresql
    tidyup-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: tidyup-elasticsearch
